create table if not exists todos (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  created_at timestamptz default now()
);

alter table todos enable row level security;

create policy "Public read access"
on todos
for select
using (true);

create policy "Public insert access"
on todos
for insert
with check (true);

create policy "Public update access"
on todos
for update
using (true);

create policy "Public delete access"
on todos
for delete
using (true);
